In [5]:
import numpy as np
 

In [6]:
A = np.array([[1,-2,5],[3,3,-1],[0,4,-2]])

print(A)

[[ 1 -2  5]
 [ 3  3 -1]
 [ 0  4 -2]]


In [ ]:
det_A = np.linalg.det (A)
print(det_A)

46.0


In [ ]:
B= np.array([[2,-2,2],[2,1,0],[3,-2,2]])
B

array([[ 2, -2,  2],
       [ 2,  1,  0],
       [ 3, -2,  2]])

In [ ]:
det_B = np.linalg.det (B)
print(det_B)

-2.0000000000000004
