In [ ]:
m_diag = np.diag([1,2,3])
m_diag

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
M_ident = np.eye(3)
M_ident

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A= np.array([[2,1],[3,4]])
print(np.linalg.det(A))

5.000000000000001


In [ ]:
inv_A = np.linalg.inv(A)
print(5*inv_A)

[[ 4. -1.]
 [-3.  2.]]


In [ ]:
A=np.array([[2,-2,2],[2,1,0],[3,-2,2]])
B=np.array([[1,-2,5],[3,3,-1],[0,4,-2]])

In [ ]:
AB = A.dot(B)
AB_inv = np.linalg.inv(AB)
AB_inv

array([[-0.25      ,  0.06521739,  0.10869565],
       [ 1.        ,  0.30434783, -0.82608696],
       [ 0.25      ,  0.10869565, -0.15217391]])

In [ ]:
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
BA_inv = B_inv@A_inv 
BA_inv

array([[-0.25      ,  0.06521739,  0.10869565],
       [ 1.        ,  0.30434783, -0.82608696],
       [ 0.25      ,  0.10869565, -0.15217391]])

In [ ]:
B=np.array([[1,-2,5],[3,3,-1],[0,4,-2]])

In [ ]:
det_B = np.linalg.det(B)
inv_B = np.linalg.inv(B)

In [ ]:
adj_B = det_B*inv_B
print(adj_B)

[[ -2.  16. -13.]
 [  6.  -2.  16.]
 [ 12.  -4.   9.]]


In [ ]:
cof_B = adj_B.T
print(cof_B)

[[ -2.   6.  12.]
 [ 16.  -2.  -4.]
 [-13.  16.   9.]]
