In [1]:
import numpy as np
Escalar = 3 
vector = np.array([1,2,3])
matriz = np.array ([[1,2,3],[4,5,6],[7,8,9]])

suma = matriz + matriz
producto_escalar = Escalar * matriz
print(producto_escalar)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
