In [1]:
import numpy as np
matriz = np.array ([[1,1,1],[1,2,3],[1,3,4]])
matriz_Trasp = matriz.T
matriz_inv = np.linalg.inv(matriz)
print(matriz_inv)
      


[[ 1.  1. -1.]
 [ 1. -3.  2.]
 [-1.  2. -1.]]
