solucion 2 examen


In [ ]:
import numpy as np

In [ ]:
A= np.array ([[7,6,8.5],[9,9.5,10],[6,7,6.5],[6,8,4],[7.5,7,7]])
print(A)

[[ 7.   6.   8.5]
 [ 9.   9.5 10. ]
 [ 6.   7.   6.5]
 [ 6.   8.   4. ]
 [ 7.5  7.   7. ]]


para la nota 1 se un punto mas a cada estudiante (+1) y para la nota 2 se suman 5 puntos a cada estudiante (+5)

In [ ]:
A= np.array ([[7+1,6+5,8.5],[9+1,9.5+5,10],[6+1,7+5,6.5],[6+1,8+5,4],[7.5+1,7+5,7]])
print(A)

[[ 8.  11.   8.5]
 [10.  14.5 10. ]
 [ 7.  12.   6.5]
 [ 7.  13.   4. ]
 [ 8.5 12.   7. ]]


In [39]:
A = np.array ([[7,6,8.5],[9,9.5,10],[6,7,6.5],[6,8,4],[7.5,7,7]])
B = np.dot(A,0.9)
print(B)

[[6.3  5.4  7.65]
 [8.1  8.55 9.  ]
 [5.4  6.3  5.85]
 [5.4  7.2  3.6 ]
 [6.75 6.3  6.3 ]]


In [40]:
A = np.array ([[7,],[9],[6],[6],[7.5]])
B = np.dot(A,0.3)
print(B)

[[2.1 ]
 [2.7 ]
 [1.8 ]
 [1.8 ]
 [2.25]]


In [41]:
A = np.array ([[6,],[9.5],[7],[8],[7]])
C = np.dot(A,0.3)
print(C)

[[1.8 ]
 [2.85]
 [2.1 ]
 [2.4 ]
 [2.1 ]]


In [43]:
A = np.array ([[8.5],[10],[6.5],[4],[7]])
D = np.dot(A,0.4)
print(D)

[[3.4]
 [4. ]
 [2.6]
 [1.6]
 [2.8]]


In [45]:
E = np.array (B+C+D)
print(E)

[[7.3 ]
 [9.55]
 [6.5 ]
 [5.8 ]
 [7.15]]


solucion pregunta 4 Examen algebra lineal

In [ ]:
import numpy as np
Matriz = np.arange (9)
np.random.shuffle (Matriz)
Matriz = Matriz.reshape((3,3))
print(Matriz)

[[1 0 8]
 [3 7 5]
 [2 6 4]]


In [ ]:
B = np.array ([[1],[3],[2]])
print(B)

[[1]
 [3]
 [2]]


In [ ]:
inv = np.linalg.inv(Matriz)
inv

array([[-0.06666667,  1.6       , -1.86666667],
       [-0.06666667, -0.4       ,  0.63333333],
       [ 0.13333333, -0.2       ,  0.23333333]])

In [ ]:
det= np.linalg.det(Matriz)
det

30.000000000000014

In [ ]:
adj = det*inv
print(adj)

[[ -2.  48. -56.]
 [ -2. -12.  19.]
 [  4.  -6.   7.]]


In [ ]:
cof = adj.T
print(cof)

[[ -2.  -2.   4.]
 [ 48. -12.  -6.]
 [-56.  19.   7.]]
