In [2]:
matrix_aux = ([4,6,2,9],[5,8,6,1],[7,2,5,10],[27,12,25,15])
            
print(matrix_aux[2][1])

print(matrix_aux[1][0])

print(matrix_aux)

# Calcular la suma de los elementos de la matrix
sumEleMat=0
for c in range(4):
    for f in range (4):
        sumEleMat=sumEleMat+matrix_aux[c][f]
        print("la suma es : ",sumEleMat)
    print("la suma ciclo externo es:", sumEleMat)
    

2
5
([4, 6, 2, 9], [5, 8, 6, 1], [7, 2, 5, 10], [27, 12, 25, 15])
la suma es :  4
la suma es :  10
la suma es :  12
la suma es :  21
la suma ciclo externo es: 21
la suma es :  26
la suma es :  34
la suma es :  40
la suma es :  41
la suma ciclo externo es: 41
la suma es :  48
la suma es :  50
la suma es :  55
la suma es :  65
la suma ciclo externo es: 65
la suma es :  92
la suma es :  104
la suma es :  129
la suma es :  144
la suma ciclo externo es: 144


In [3]:
import numpy as np 

In [4]:
n = 4
A = np.array ([[4,6,2,9],[5,8,6,1],[7,2,5,10],[27,12,25,15]])
print(A)

[[ 4  6  2  9]
 [ 5  8  6  1]
 [ 7  2  5 10]
 [27 12 25 15]]


In [6]:
sum_first_diagonal = sum(A[i][i] for i in range(n))
sum_second_diagonal = sum(A[i][n-i-1] for i in range(n))
print(str(sum_first_diagonal))
print(str(sum_second_diagonal))

32
44
