In [ ]:
import numpy as np

In [ ]:
A= np.array([[1,2,3],[4,5,6],[7,8,0]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [ ]:
A_inv = np.linalg.inv(A)
A_inv

array([[-1.77777778,  0.88888889, -0.11111111],
       [ 1.55555556, -0.77777778,  0.22222222],
       [-0.11111111,  0.22222222, -0.11111111]])

In [ ]:
det_A = np.linalg.det(A)
det_A

27.0

In [ ]:
adj_A = det_A*inv_A
print(adj_A)

[[-48.  24.  -3.]
 [ 42. -21.   6.]
 [ -3.   6.  -3.]]


In [19]:
cof_A = adj_A.T
print(cof_A)

[[-48.  42.  -3.]
 [ 24. -21.   6.]
 [ -3.   6.  -3.]]
