In [ ]:
import numpy as np

In [ ]:
A = np.array ([1,-5,4])
print(A)

[ 1 -5  4]


In [ ]:
B = np.array ([[3],[0],[2]])
print(B)

[[3]
 [0]
 [2]]


In [ ]:
C = np.array ([[3,2,5],[2,-1,4],[-1,2,1]])
print(C)

[[ 3  2  5]
 [ 2 -1  4]
 [-1  2  1]]


In [ ]:
D = np.array ([[2,3,4],[-1,5,6],[2,3,0]])
print(D)

[[ 2  3  4]
 [-1  5  6]
 [ 2  3  0]]


In [ ]:
E1 = C.dot(3)
print(E1)

[[ 9  6 15]
 [ 6 -3 12]
 [-3  6  3]]


In [ ]:
E2 = A.dot(2)
print(E2)

[  2 -10   8]


In [ ]:
E3= C.dot(D)
print(E3)

[[14 34 24]
 [13 13  2]
 [-2 10  8]]


In [ ]:
def matExp(C,n):
    n -=-1
    E4 = a.copy()
    for i in range(n):
        E4 = matMul(C,-1)
    return E4

In [ ]:
E4_1 = np.linalg.matrix_power(C,-1)
print(E4_1)


[[ 0.375      -0.33333333 -0.54166667]
 [ 0.25       -0.33333333  0.08333333]
 [-0.125       0.33333333  0.29166667]]


In [ ]:
C_inv = np.linalg.inv(C)
C_inv

array([[ 0.375     , -0.33333333, -0.54166667],
       [ 0.25      , -0.33333333,  0.08333333],
       [-0.125     ,  0.33333333,  0.29166667]])

In [ ]:
det_C= np.linalg.det(C)
det_C

-24.000000000000014

In [ ]:
adj_C = det_C*C_inv
print(adj_C)

[[-9.  8. 13.]
 [-6.  8. -2.]
 [ 3. -8. -7.]]


In [ ]:
cof_C = adj_C.T
print(cof_C)

[[-9. -6.  3.]
 [ 8.  8. -8.]
 [13. -2. -7.]]


In [ ]:
F = np.eye(4)
F

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
G = np.diag([-1,3,5,8])
G

array([[-1,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  5,  0],
       [ 0,  0,  0,  8]])

In [ ]:
A = np.array ([[1/2,5,3],[3,-3/4,4],[-2,-8,7/6]])
H= np.trace(A)
print(H)

0.9166666666666667


In [ ]:
B = np.array ([[3/8,5,7],[4,2/5,1],[0,1,5/4]])
H1= np.trace(B)
print(H1)

2.025
